### ISSUE TITLE
`.adpcm_block_data` directive does not work

### ISSUE THREAD

**Issue by toyoshim** [toyoshim/z-music.js#1]
Probably `.adpcm_block_data` needs to handle file open/read/close DOSCALLs in a suitable way.
z-music.js may need to have an interface to handle a file loading callback, or just implement a default function to fetch the ZPD data via XHR.

**Comment by toyoshim** [comment]
https://github.com/toyoshim/z-music.js/commit/14af83f0659743f68f46d42734ce3c9a781256c4

**Comment by mt08xx** [comment]
It has been confirmed to work with `z-music.js v1.2.1.0` .

And found the new issue, which is related to ZPD filename.

For example,  in ZMS,  `.Adpcm_Block_Data = MoonRevenge.ZPD`
This tries to find the file '`MOONREVENGE.ZPD`'. 
( `GET MOONREVENGE.ZPD` could be seen in Browser console.)

So, ZPD filename needs to be **Uppercase** currently.
(It should be the different behavior between UN*X-based and Human68k file system.... :-| )

Will open new ticket.
