### ISSUE TITLE
ZPD may be a little broken if it was read via play()

### ISSUE THREAD

**Issue by toyoshim** [toyoshim/z-music.js#2]
See http://qiita.com/toyoshim/items/38dafc97629a98434267#comment-c044df73c5fc4f403037

**Comment by toyoshim** [comment]
If ZPD was read via .adpcm_block_data, it works fine.

**Comment by toyoshim** [comment]
https://github.com/toyoshim/z-music.js/commit/84f40b45df64e4ea4c0cd6538387daf3db9fc0d4

**Comment by mt08xx** [comment]
Confirmed it works great with `z-music.js v1.2.1.0`. :-)
